# Generated by Django 4.0.5 on 2022-06-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthpizza', '0002_rename_content_per_gram_food_nutr_content_content_per_100_gram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food_Nutr_content',
        ),
    ]
