# Generated by Django 4.0.5 on 2022-06-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthpizza', '0004_food_nutr_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='simple',
            field=models.CharField(default='goitre', max_length=50),
        ),
        migrations.AddField(
            model_name='food',
            name='simple',
            field=models.CharField(default='cheese', max_length=50),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='simple',
            field=models.CharField(default='vitD', max_length=50),
        ),
    ]
