# Generated by Django 4.0.5 on 2022-08-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthpizza', '0005_disease_simple_food_simple_nutrient_simple'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.CharField(default='cheese', max_length=50),
        ),
    ]
