# Generated by Django 4.0.5 on 2022-11-02 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthpizza', '0006_food_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Requested_Additions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_edit', models.CharField(max_length=40)),
                ('edit_info', models.CharField(max_length=300)),
                ('edit_type', models.CharField(max_length=10)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
